### ISSUE TITLE
Criar template para aplicações VueJS

### ISSUE THREAD

**Issue by tanisesarmento** [plingbr/vue-cli-template#1]
Precisamos gerar um template base para inicializar novas aplicações VueJS na Pling, tal como o Painel do Cliente que deverá ser em VueJS já.

Essa issue pode ser endereçada ao @ezequielmross pois já alinhamos.

**Comment by tanisesarmento** [comment]
Estimativa alterada durante double-check.

**Comment by ezequielferr** [comment]
TDT: 11 hs

**Comment by tanisesarmento** [comment]
@felipekm Podes auxiliar na validação?

**Comment by felipekm** [comment]
Validado.
